/**
 * @file add_two_ints_client.cpp
 * @author César
 * Example of creating a client. ROS tutorials
 */

#include "ros/ros.h"
#include "beginner_tutorials/AddTwoInts.h"
#include <cstdlib>

int main(int argc, char **argv)
{
    ros::init(argc, argv, "add_two_ints_client");
    if (argc != 3)
    {
        ROS_INFO("usage: add_two_ints_client X Y");
        return 1;
    }

    ros::NodeHandle n;
    ros::ServiceClient client = n.serviceClient<beginner_tutorials::AddTwoInts>("add_two_ints");/**< This create a client for the add_two_ints service. The ros::ServiceClient object is used to call the service later on.*/
    beginner_tutorials::AddTwoInts srv;/**< Here, we instantiate an autogenerated service class*/
    srv.request.a = atoll(argv[1]);/**< Assign values into its request memeber*/
    srv.request.b = atoll(argv[2]);
    if (client.call(srv))/**< This actually calls the service. Service calls are BLOCKING!!*/
    {
        ROS_INFO("Sum: %ld", (long int)srv.response.sum);
    }
    else
    {
        ROS_ERROR("Failed to call service add_two_ints");
        return 1;
    }

    return 0;
}
